<?php

use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function learning_hello_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.learning_hello':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is an example hook.') .
        '</p>';
      return $output;
    default:
  }
}
